export { Delete } from './Api/Delete'
export { Get } from './Api/Get'
export { Head } from './Api/Head'
export { Patch } from './Api/Patch'
export { Post } from './Api/Post'
export { Put } from './Api/Put'
